"""empty message

Revision ID: 3ad9ad14c3d
Revises: None
Create Date: 2015-10-22 22:34:24.765253

"""

# revision identifiers, used by Alembic.
revision = '3ad9ad14c3d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
